In [2]:
import numpy as np

### Markov Chain
- Set of possible states
- Initial state
- Transition Model

In [5]:
# transition matrix
T = np.array([[0.9, 0.1], [0.5, 0.5]])

# T after some steps
T_3 = np.linalg.matrix_power(T, 3)
T_50 = np.linalg.matrix_power(T, 50)
T_100 = np.linalg.matrix_power(T, 100)

print(T_3)
print(T_50)
print(T_100)

[[0.844 0.156]
 [0.78  0.22 ]]
[[0.83333333 0.16666667]
 [0.83333333 0.16666667]]
[[0.83333333 0.16666667]
 [0.83333333 0.16666667]]


In [6]:
# initial distribution
v = np.array([[1, 0]])

# distribution after some steps
v_1 = np.dot(v, T)
v_3 = np.dot(v, T_3)
v_50 = np.dot(v, T_50)
v_100 = np.dot(v, T_100)

print(v_1)
print(v_3)
print(v_50)
print(v_100)

[[0.9 0.1]]
[[0.844 0.156]]
[[0.83333333 0.16666667]]
[[0.83333333 0.16666667]]


### Markov Decision Process
- Set of possible states
- Initial state
- Set of possible actions
- Transition model
- Reward function